### ISSUE TITLE
[Research] Standalone DFU app

### ISSUE THREAD

**Issue by erichelgeson** [erichelgeson/BlueSCSI-Updater#3]
DFU-Buddy - currently crashes at startup - Could be due to STM32duino-bootloader response string
https://github.com/sourcebox/dfu-buddy/

dfu_java - got this one to recognize the bootloader, but fails attempting to write, seems promising so far.
https://github.com/rusefi/dfu_java

Build bindings from swift/c# app right into dfu-util.

Others:

https://github.com/keirf/Greaseweazle/wiki/Firmware-Update#f1-update-procedure - gw has a built in updater in their cli

https://github.com/vpelletier/python-dfu - old, harder to package

**Comment by aihk** [comment]
This https://github.com/fauxpark/qmk_toolbox can be changed to the visual update software available from BlueSCSI. I use this firmware to update the st when I make a keyboard. The update is also completed under the guidance of STM32duino-bootloader, which is very convenient

**Comment by erichelgeson** [comment]
Thanks for the pointer @aihk - I tried it out but it currently is failing on Windows with Maple DFU - but looks promising! https://github.com/qmk/qmk_toolbox/issues/375 

Edit: n/m, i had the wrong driver selected for Maple 003 - it should have been set to WinUSB with Zadig - works great!
