### ISSUE TITLE
[Research] Update via bin file on SD card

### ISSUE THREAD

**Issue by erichelgeson** [erichelgeson/BlueSCSI-Updater#4]
Like floppyemu, put a bin file on the sd card and allow the bootloader to do the reprogramming at startup if found. No idea how to go about it but would eliminate the need for dfu flashing.

**Comment by aihk** [comment]
Hope this helps you https://github.com/caoliuchao/STM32F103-bootLoader/blob/f879bf989913ab0d07caabbb9bfb24b6e45a634a/Project/main.c

**Comment by erichelgeson** [comment]
Thanks! This looks very similar to an approach I tried a few months ago but got stuck. Looks like they use a sdio and I'm not familiar with this project structure - but maybe I can pull something out and port it over.

**Comment by ayourk** [comment]
Suggestion:  make the filename: "bluescsi.bin" and check for the version info in the code.
