### ISSUE TITLE
Bluescsi updater should be using newest firmware

### ISSUE THREAD

**Issue by jacexpo** [erichelgeson/BlueSCSI-Updater#7]
The bluescsi updater is currently set only to update to the  older 2022 firmware. The 2023 July firmware should be added in its place.

This requires the .bin file be changed in the utils/ directory as well as the calling scripts

https://github.com/erichelgeson/BlueSCSI-Updater/tree/main/utils)/flash-bluescsi-firmware-usb.sh and

https://github.com/erichelgeson/BlueSCSI-Updater/tree/main/utils)/flash-bluescsi-firmware-usb.bat

**Comment by erichelgeson** [comment]
Thanks - this will be the last update to this updater as I recommend people use the QMK-Toolbox as it works much better/easier to install. 

fbbe928

**Comment by jacexpo** [comment]
Just so you know I love this product - thank you for continuing to support
the 1.1 models.
